a = float(input())
b = float(input())
total = abs(a) + abs(b)
difference = abs(a) - abs(b)
product = abs(a) * abs(b)
quotient = abs(a) / abs(b)
print(total)
print(difference)
print(product)
print(quotient)
