x1 = float(input())
y1 = float(input())
x2 = float(input())
y2 = float(input())
side_a = abs(x2 - x1)
side_b = abs(y2 - y1)
perimeter = 2 * (side_a + side_b)
area = side_a * side_b
print(perimeter)
print(area)
